### ISSUE TITLE
Create UI for allowing students to post anonymously

### ISSUE THREAD

**Issue by lwunder** [CMU-313/fall23-nodebb-op#4]
**Estimated Effort:** 5 hrs
**Dependencies:** N/A
**Milestones:** Sprint 1
**Acceptance criteria:** Some sort of UI option that allows students to choose whether or not their post is anonymous.

- This should work for all types of student posts (e.g. original posts, follow-ups, etc.)
- Does not need to be present for instructors.

Other Notes: Can decide what the UI will look like (right now, considering dropdown or checkbox)

**Comment by SerenaYaoo** [comment]
09/16 (local)

- added 'Hide Name' button in specific post page
- displayed pseudo-random anonymous name as display name

09/21 (local)
- added 'Post as Anonymous' button

**Comment by xavier-xia-99** [comment]
most recent update : #30
