### ISSUE TITLE
Make anonymous username generator for students

### ISSUE THREAD

**Issue by lwunder** [CMU-313/fall23-nodebb-op#5]
**Estimated Effort:** 2 hrs
**Dependencies:** N/A
**Milestones:** Sprint 1
**Acceptance criteria:** A method that makes a random username that is _unique_ for a particular post BUT is associated with the same user throughout the post thread. The anonymous username should not necessarily be associated with the same student across different threads.

For example using Anonymous_{Animals} `Annoymous_id`

**Comment by xavier-xia-99** [comment]
closed due to narrowing scope
